### PR TITLE
fix: Pip servers handle config changes gracefully

### LINKED ISSUE #137: Pip server conflicts with configured servers
If a user configures a server on port `10001` and then attempts to start a pip managed server, a toast message is shown

"Unexpected server state for managed server: 'http://localhost:10001/'". Clicking again then attempts `10002`

A few issues here:
1. The error message is not helpful
2. In the case of an error, I'd expect the pip port would not increment but would put it back in the set to try again
3. The default pip server range is very likely to conflict with ports that users choose for their own servers
4. If user changes configuration after connected to a Pip server, the connection is lost and can't be reconnected

We should have pip port detection be smarter to avoid ports configured for core servers (probably should get rid of the current hard coded 4 ports)

### PR DESCRIPTION
**Pull request by bmingles**
- Pip servers now support a larger range of ports
- Configured servers now reserve ports so pip servers won't touch them
- If configuration changes such that a running pip server becomes reserved by config, the pip server will be shut down
- Keep server state for running pip servers on config change so that generated PSKs can continue to be used

**Testing**
I used a configuration targetting the first few ports starting at `10000`

**Initial config (servers all commented out)**
```jsonc
"deephaven.coreServers": [
  // "http://localhost:10000/",
  // "http://localhost:10001/",
  // "http://localhost:10002/",
  ```
  
**Pip server port becomes reserved via config change**
- Start a pip server (should start on port `10000`)
- Modify config by uncommenting `"http://localhost:10000/"`
- Pip server should automatically stop. `localhost:10000` should be listed under "Stopped" and no longer under "Managed"

**Start server outside of extension**
- Start a server on port `10000` (outside of extension)
- Refreshing server panel should show it as running and allow connection

**Arbitrary config change**
- Start a pip server
- Make a config change that doesn't affect the port of the running server
- Pip server should remain connected and usable

resolves #137

### CODE REVIEW

File: src/controllers/PipServerController.ts [hunk 1]
```diff
@@ -127,10 +127,50 @@ export class PipServerController implements Disposable {
...
-  getAvailablePorts = (): Port[] => {
-    return [...this._portRange]
-      .filter(port => !this._serverUrlTerminalMap.has(port))
-      .sort();
+  /**
+   * Gets the next available port for starting a pip server.
+   * @returns A port number or `null` if no ports are available.
+   */
+  getNextAvailablePort = (): Port | null => {
+    for (let i = 10000; i < 10050; ++i) {
```
Comment (mofojed) [inline src/controllers/PipServerController.ts:135]: Why stop at 10050? Why not like 10999?

**Review by mofojed — APPROVED** [review]

File: src/controllers/PipServerController.ts (hunk 1 above)
Comment (bmingles) [reply src/controllers/PipServerController.ts:135]: It was arbitrary. Figured 50 was even higher than system resources would probably allow
